import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavBar() {
  // クライアントコンポーネントでパスを取得
  const pathname = typeof window !== "undefined" ? window.location.pathname : "";
  return (
    <nav className="w-full flex justify-center items-center py-4 bg-white border-b border-blue-50 mb-8 shadow-sm sticky top-0 z-20">
      <div className="flex gap-4">
        <Link href="/main" className={`px-4 py-2 rounded-lg font-medium transition-colors ${pathname === "/main" ? "bg-blue-100 text-blue-700" : "text-gray-500 hover:bg-blue-50"}`}>思考する</Link>
        <Link href="/logs" className={`px-4 py-2 rounded-lg font-medium transition-colors ${pathname === "/logs" ? "bg-blue-100 text-blue-700" : "text-gray-500 hover:bg-blue-50"}`}>ログ一覧</Link>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* ナビゲーションバー */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
